#
#  Copyright 2019 Christopher Di Bella
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
task:
  container:
    matrix:
      - image: cjdb/cirrus-cpp:bionic
    cpu: 4
    memory: 4G
  env:
    matrix:
      - PROFILE: gcc-5
        CODE_COVERAGE: gcov
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS:
      - PROFILE: gcc-6
        CODE_COVERAGE: gcov
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS:
      - PROFILE: gcc-7
        CODE_COVERAGE: gcov
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS:
      - PROFILE: gcc-8
        CODE_COVERAGE: gcov
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS:
      - PROFILE: clang-4
        CODE_COVERAGE: LLVMSourceCoverage
      - PROFILE: clang-4-libcxx
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-4-libcxx-msan
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: MemorySanitizerWithOrigins;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-5
        CODE_COVERAGE: LLVMSourceCoverage
      - PROFILE: clang-5-libcxx
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-5-libcxx-msan
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: MemorySanitizerWithOrigins;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-6
        CODE_COVERAGE: LLVMSourceCoverage
      - PROFILE: clang-6-libcxx
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-6-libcxx-msan
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: MemorySanitizerWithOrigins;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-7
        CODE_COVERAGE: LLVMSourceCoverage
      - PROFILE: clang-7-libcxx
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-7-libcxx-msan
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: MemorySanitizerWithOrigins;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-8
        CODE_COVERAGE: LLVMSourceCoverage
      - PROFILE: clang-8-libcxx
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: AddressSanitizer;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
      - PROFILE: clang-8-libcxx-msan
        CODE_COVERAGE: LLVMSourceCoverage
        REQUIRED_SANITIZERS: MemorySanitizerWithOrigins;UndefinedBehaviorSanitizer
        OPTIONAL_SANITIZERS: ControlFlowIntegrity
    matrix:
      - BUILD_TYPE: Debug
        ENABLE_CLANG_TIDY: On
      - BUILD_TYPE: Release
        ENABLE_CLANG_TIDY: On
    matrix:
     - ENABLE_RELEASE_SANITIZERS: Off
     - ENABLE_RELEASE_SANITIZERS: On
  preconfig_script:
    - mkdir build
  conan_config_install_script:
    - cd build
    - conan config install ../conan
  conan_install_script:
    - cd build
    - conan install .. --profile=${PROFILE} --settings build_type=${BUILD_TYPE} --build missing
  conan_build_configure_script:
    - cd build
    - conan build .. --configure
    - cmake .. -Dbasic_project_ENABLE_CLANG_TIDY=${ENABLE_CLANG_TIDY}
    - cmake .. -Dbasic_project_CODE_COVERAGE=${CODE_COVERAGE}
    - cmake .. -Dbasic_project_REQUIRED_SANITIZERS="${REQUIRED_SANITIZERS}" -Dbasic_project_OPTIONAL_SANITIZERS="${OPTIONAL_SANITIZERS}"
    - cmake .. -Dbasic_project_SANITIZE_RELEASE="${ENABLE_RELEASE_SANITIZERS}"
  build_script:
    - cd build
    - ninja -v
  tests_script:
    - cd build
    - ctest -j 8 --output-on-failure
  clang_format_script:
    - bash config/hooks/clang-format.sh
